#!/bin/bash
# WARNING: This file is auto-generated by snipinator. Do not edit directly.
# SOURCE: `mdremotifier/examples/simple_example.sh.jinja2`.

# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -e -x -v -u -o pipefail
set +v
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color
PS4="${GREEN}$ ${NC}"

: ECHO_SNIPPET_START
# SNIPPET_START
# View the template file.
cat "mdremotifier/examples/SIMPLE.md"

python -m mdremotifier.cli  \
  -i "mdremotifier/examples/SIMPLE.md" \
  --url-prefix https://github.com/realazthat/mdremotifier/blob/master/ \
  --img-url-prefix https://raw.githubusercontent.com/realazthat/mdremotifier/master/ \
  -o "mdremotifier/examples/SIMPLE.remotified.md"

# View the remotified file.
cat "mdremotifier/examples/SIMPLE.remotified.md"

# SNIPPET_END
: ECHO_SNIPPET_END
